stingray_core_control_node:
  ros__parameters:
    controllers.surge.K_p: 1.0
    controllers.surge.K_1: 4.0
    controllers.surge.K_2: 2.8
    controllers.surge.K_i: 0.0
    controllers.surge.I_min: -5.0
    controllers.surge.I_max: 5.0
    controllers.surge.out_sat: 1000.0
    controllers.surge.ap_K: 1.0
    controllers.surge.ap_T: 0.01
    controllers.sway.K_p: 0.8
    controllers.sway.K_1: 1.0
    controllers.sway.K_2: 0.1
    controllers.sway.K_i: 0.01
    controllers.sway.I_min: -0.2
    controllers.sway.I_max: 0.2
    controllers.sway.out_sat: 1.0
    controllers.sway.ap_K: 1.0
    controllers.sway.ap_T: 0.3
    controllers.heave.K_p: 1.0
    controllers.heave.K_1: 4.0
    controllers.heave.K_2: 3.5
    controllers.heave.K_i: 1.0
    controllers.heave.I_min: -0.3
    controllers.heave.I_max: 0.3
    controllers.heave.out_sat: 200.0
    controllers.heave.ap_K: 1.0
    controllers.heave.ap_T: 0.4
    controllers.roll.K_p: 1.0
    controllers.roll.K_1: 2.0
    controllers.roll.K_2: 1.0
    controllers.roll.K_i: 1.5
    controllers.roll.I_min: -20.0
    controllers.roll.I_max: 20.0
    controllers.roll.out_sat: 200.0
    controllers.roll.ap_K: 1.0
    controllers.roll.ap_T: 0.005
    controllers.roll.grav_bias: 0.0
    controllers.roll.grav_gain: 0.0
    controllers.roll.grav_offset_deg: 0.0
    controllers.pitch.K_p: 1.1
    controllers.pitch.K_1: 1.1
    controllers.pitch.K_2: 0.025
    controllers.pitch.K_i: 0.04
    controllers.pitch.I_min: -0.4
    controllers.pitch.I_max: 0.4
    controllers.pitch.out_sat: 50.0
    controllers.pitch.ap_K: 1.0
    controllers.pitch.ap_T: 1.0
    controllers.pitch.grav_bias: 0.0
    controllers.pitch.grav_gain: 0.0
    controllers.pitch.grav_offset_deg: 0.0
    controllers.yaw.K_p: 0.6
    controllers.yaw.K_1: 4.4
    controllers.yaw.K_2: 1.4
    controllers.yaw.K_i: 0.6
    controllers.yaw.I_min: -0.01
    controllers.yaw.I_max: 0.01
    controllers.yaw.out_sat: 200.0
    controllers.yaw.ap_K: 1.0
    controllers.yaw.ap_T: 0.0
