stingray_core_control_node:
  ros__parameters:
    surge_upper_left_surge: -1
    surge_upper_left_sway: 0
    surge_upper_left_heave: 0
    surge_upper_left_roll: 0
    surge_upper_left_pitch: 1
    surge_upper_left_yaw: 0
    depth_front_right_surge: 0
    depth_front_right_sway: 0
    depth_front_right_heave: 1
    depth_front_right_roll: 1
    depth_front_right_pitch: 0
    depth_front_right_yaw: 0
    sway_front_surge: 0
    sway_front_sway: -1
    sway_front_heave: 0
    sway_front_roll: 0
    sway_front_pitch: 0
    sway_front_yaw: -1
    depth_back_right_surge: 0
    depth_back_right_sway: 0
    depth_back_right_heave: -1
    depth_back_right_roll: -1
    depth_back_right_pitch: 0
    depth_back_right_yaw: 0
    surge_upper_right_surge: 1
    surge_upper_right_sway: 0
    surge_upper_right_heave: 0
    surge_upper_right_roll: 0
    surge_upper_right_pitch: -1
    surge_upper_right_yaw: 0
    sway_back_surge: 0
    sway_back_sway: -1
    sway_back_heave: 0
    sway_back_roll: 0
    sway_back_pitch: 0
    sway_back_yaw: 1
    depth_back_left_surge: 0
    depth_back_left_sway: 0
    depth_back_left_heave: -1
    depth_back_left_roll: 1
    depth_back_left_pitch: 0
    depth_back_left_yaw: 0
    depth_front_left_surge: 0
    depth_front_left_sway: 0
    depth_front_left_heave: 1
    depth_front_left_roll: -1
    depth_front_left_pitch: 0
    depth_front_left_yaw: 0
    surge_lower_left_surge: 1
    surge_lower_left_sway: 0
    surge_lower_left_heave: 0
    surge_lower_left_roll: 0
    surge_lower_left_pitch: 1
    surge_lower_left_yaw: 0
    surge_lower_right_surge: 1
    surge_lower_right_sway: 0
    surge_lower_right_heave: 0
    surge_lower_right_roll: 0
    surge_lower_right_pitch: 1
    surge_lower_right_yaw: 0
